### PR TITLE
Specify using Node buffer by importing it

### PR DESCRIPTION
**Pull request by McSneaky**
### ❓ Type of change

- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

It makes easier to use Adonis HTTP module across different JS runtimes

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @McSneaky! 👋🏻 

Thanks for the PR! May you change your `"` to `'` and move this import at the top?

**Comment by McSneaky** [comment]
Sure, lemme see how to edit it.. Was using Github web UI

**Comment by RomainLanz** [comment]
Great! We are still missing the change for the test file. Otherwise CI will fail. 😄

**Review by McSneaky — COMMENTED** [review]
Move Node buffer import to top

**Comment by McSneaky** [comment]
^ was supposed to be commit message..

Lemme open another PR and do it from local all correctly.. Using Github "." is kinda confusing when using it for existing PRs and forks..

**Pull request closed without merging**
