### PR TITLE
Route : Add locale and make findRouteOrFail public

### PR DESCRIPTION
**Pull request by Reptiluka**
## Proposed changes
The old method lookup(routeIdentifier, forDomain) , was deleted during an old refactoring and we can't look if a route exist.
Also, adding the locale into the route can be helpful.
Example I have UserController.login, and want to use it for english and french, only the last one is taken I think. (using route() in view or with makeUrl etc.)

Here an example : 

```
Route.group(() => {
  Route.get('/', 'MainController.index')
  Route.get('/connexion', 'UsersController.login')
  Route.get('/deconnexion', 'UsersController.logout')
  Route.post('/connexion', 'UsersController.login_form')
  Route.get('/inscription', 'UsersController.register')
  Route.post('/inscription', 'UsersController.store')
  Route.get('/tarification', 'MainController.pricing')
}).prefix('/fr').lang('fr')

```
```
Route.group(() => {
  Route.get('/', 'MainController.index')
  Route.get('/login', 'UsersController.login')
  Route.get('/logout', 'UsersController.logout')
  Route.post('/login', 'UsersController.login_form')
  Route.get('/signup', 'UsersController.register')
  Route.post('/signup', 'UsersController.store')
  Route.get('/pricing', 'MainController.pricing')
}).prefix('/en').lang('en')
```

We have two solution :
### First way, Adding the local into the route : 
**The following code is added manually and is not in the PR, but it can be added somewhere to be permanent**
In AppProvider.ts , inside boot() :
```
    //Mode with locale include into routes
    Routes.RouteGroup.macro('lang', function (lang) {
      this.routes.forEach((route: Route) => {
        //Put the name of the handler into the routes
        //Actually the ressource do that, but we can't with a group, so I created that function
        //If the route name is empty, we can't do .as() , so we init the name
        route.as(route.toJSON().handler.toString())
      });

      //Once the name is init, we can do a .as() , with the locale
      //Ex. Controller.action become locale.Controller.action, example fr.UsersController.login and en.UsersController.login
      this.as(lang)
      return this
    })
  }
```

And in DetectUserLocale I added : 
```
//Override of the route() into view
      ctx.view.share({route : (routeIdentifier: string, params?: any, options?: any) => {
      //Here is if we take that solution, with the locale inside the name, but I prefer the locale as a parameter
        const locale_url = `${ctx.i18n.locale}.${routeIdentifier}`
        let route_exist
        try {
        //At this moment, we CAN'T use .findRouteOrFail() because is private, I make it public in the PR
          Route.builder().findRouteOrFail(locale_url)
          route_exist = true
        } catch (error) {
          route_exist = false
        }
        
        //Return the route with the current locale if exist, else just the route
        return route_exist ? Route.makeUrl(locale_url, params, options) : Route.makeUrl(routeIdentifier, params, options)
      }})
```

### Second method : Add the locale dirrectly into the route
In AppProvider.ts , inside boot() :
Instead of the previous code where the locale was added into the name, we can have this :
```
 Routes.RouteGroup.macro('lang', function (lang) {
     this.routes.forEach((route: Route) => {
       route.locale = lang
     });
     return this
   })
   }
```
With the code in the PR, now we can use this : 
`Route.makeUrl("UsersController.login", {locale: ctx.i18n.locale})`
So the url will be /fr/connexion or /en/login
**Also** : Maybe if a user go dirrectly to /en/login and his default langage is for example french, maybe we want all the /en pages stay in english, so we can change the locale deppending where the user go. If a French user goes in /en/login , I don't want he see /en in the url bar, and all the texts is in french.

**Also :**
If Google Bot crawl /fr/connexion, it will not take the "default locale" from .env, or his Accept-Langage, because Google is always in english. So when he will crawl /fr/connexion, the page will be in French.

You can reply here or dm me on Discord : Reptiluka#4993

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/adonisjs/http-server/blob/master/.github/CONTRIBUTING.md) doc
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by thetutlage** [comment]
Thanks for the PR @Reptiluka 

Couple of issues here.

- The PR is trying to add multiple things. Let's keep PR's focused to only one thing at a time.
- 2nd. At the router level there is no concept of defining locales. Therefore, I doesn't feel right to allow defining locales when making URLs

As you have shown, this can be easily be done as an external package by extending the Router API. Infact, I will encourage doing this way to showcase that framework can be extend from outside

**Comment by Reptiluka** [comment]
@thetutlage Yeah sorry for the multiple commits, it was because I started one first, and for the second I needed the function to have if the route exist 🙂

I thought I saw another package who use the locale in the context, and it was not i18n package? Also as the feature is important, I think it should be added to the framework directly and not an optional package, that's why I put it there 

Also I don't know how to make a package ☹️, it takes me few effort only to find things at the right place as in the PR, so create a package about that will be difficult I think.

So it was more for the idea. As I'm French, I start my project always in French, but for the international community I have no choice to make an English version, while others only make an English version so they don't see the problem I have 🙂

At this time with only the controller and action name, the generated route is always the last defined I think, the locale can solve that.

And as I say in the description, I want a user who go on /fr link they see the page in French, same things for /en in English, so embed the locale into the page is a good idea I think.

Also for the little script to init route name for a group.

And the last point for the Google Crawl bot, where I don't want he crawl my /fr page in English 🙂

I really need this and I think it's important and can be useful. Don't know if you can help me with this ? The PR was more for the idea and the problem I had, feel free to make the same kind of solution in the rights package if you can.

Thanks! 🙂

**Comment by thetutlage** [comment]
I understand that you need this feature. But, as the creator of the framework I have to draw a line and let the surrounding ecosystem grow. If everything stops to "We don't know how to create a package, so add it to the core", then after a point it will become a nightmare for me to maintain the framework.

So, I will skip this for now. You or anyone can take inspiration from existing packages and try to build something that contributes back to the ecosystem.

Again, it is not about whether the feature is important or not. It is more about pushing the community to contribute back with the features they want

**Comment by Reptiluka** [comment]
@thetutlage 
I will try my best 🙂
By adding to the core I mean, at this time if someone wants to make a "big pro multimillion dollar company" like I was want, it need that feature. Yes we can translate the website but it need that. So that's why I think it's necessary and not only an option.

But I understand you need to keep control and maintain all things as you can.
In few years I will be able to donate and I will pay you a complete team, stay tuned 😉 I will be a platinum sponsor like Shopify or Airbnb do to small projects.

Thanks for all the works, AdonisJs is the best! 🙂

**Pull request closed without merging**
