### PR TITLE
fix(response): adaptation function body params in terms of http status

### PR DESCRIPTION
**Pull request by LeadcodeDev**
image

## Types of changes

What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/adonisjs/http-server/blob/master/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by thetutlage** [comment]
A quick question. Does accepting the argument to `generateEtag` makes sense when we are not accepting any body?

**Comment by LeadcodeDev** [comment]
After thinking about it, the `generateEtag` parameter is useless for certain methods, we will update the pull request

**Comment by thetutlage** [comment]
Thanks. Looks great now :)

**Comment by thetutlage** [comment]
Also, will be part of the major release, since some codebases maybe relying on those parameters, even though they were useless

**Pull request merged**
